# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nours-notebooks',
                'doc_host': 'https://ronrio.github.io',
                'git_url': 'https://github.com/ronrio/nours-notebooks',
                'lib_path': 'nours_notebooks'},
  'syms': {'nours_notebooks.core': {'nours_notebooks.core.foo': ('core.html#foo', 'nours_notebooks/core.py')}}}
