# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_probablistic_state_estimation.ipynb.

# %% auto 0
__all__ = ['DDist']

# %% ../nbs/01_probablistic_state_estimation.ipynb 2
class DDist:
    def __init__(self, dictionary):
        self.d = dictionary
